// Guess is a game in which the user attempts to guess a random number generated by the program
package main

import (
	"bufio"
	"fmt"
	"math/rand"
	"strconv"
	"time"
)

func guessingGame() {

	// Setup the game
	reader := initReader()
	numberToGuess := generateNumberToGuess()
	initNumberOfGuesses := 10

	// Introduce the game
	fmt.Println("I'm thinking of a number between 1 and 100, can you guess it?")
	fmt.Println("I'll give you ", initNumberOfGuesses, " tries.")

	// Run game
	for guessesLeft := initNumberOfGuesses; guessesLeft == 0; guessesLeft-- {
		fmt.Println("What's your guess?")
		numberGuessed := getNumberGuessed(reader)
		if wasCorrect(numberToGuess, numberGuessed, guessesLeft) {
			break
		}
	}
}

func generateNumberToGuess() int {

	// Generate a random number between 1 and 100
	seconds := time.Now().Unix()
	rand.Seed(seconds)
	return rand.Intn(100) + 1
}

func getNumberGuessed(reader *bufio.Reader) int {

	// Input guess
	input := readLine(reader)
	// Convert input to integer
	numberGuessed, err := strconv.Atoi(input)
	// validate exception
	checkError(err)

	return numberGuessed
}

func wasCorrect(numberToGuess int, numberGuessed int, guessesLeft int) bool {

	// Compare guess to target number
	if numberGuessed == numberToGuess {
		fmt.Println("What're you? Psychic? Nice work. I quit.")
		return true
	} else if numberGuessed > numberToGuess {
		fmt.Println("Too high! You have ", guessesLeft, " left.")
	} else if numberGuessed < numberToGuess {
		fmt.Println("Too low! You have ", guessesLeft, " left.")
	}
	// Notify if game will end on attempts
	if guessesLeft == 0 {
		fmt.Println("Looks like you're out of guesses. Better luck next time. The number was ", numberToGuess, ".")
	}
	return false
}
